version: '3'

services:
  vk-service:
    build:
      context: ./vk-service
    ports:
      - "3000:3000"
    networks:
      - my-network

  instagram-service:
    build:
      context: ./instagram-service
    ports:
      - "4000:4000"
    networks:
      - my-network

  api-gateway:
    build:
      context: ../ap-gateway
    ports:
      - "5000:5000"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge